version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: custodywallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5000:80"  # 5000 на хосте, 80 в контейнере
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:
