version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: custodywallet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1221
      POSTGRES_DB: custodywallet
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custodywallet-api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=custodywallet;Username=postgres;Password=postgres"
    ports:
      - "5000:80"
    command: >
      /bin/sh -c "
      dotnet tool install --global dotnet-ef --version 8.0.0 && 
      export PATH=\"$PATH:/root/.dotnet/tools\" &&
      dotnet ef database update --no-build &&
      dotnet CustodyWallet.dll
      "

volumes:
  pgdata:
